### ISSUE TITLE
Cache size?

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-integration#1]
For v1, only caching and providing user id as context, not whole user doc. 

How many MB default cache size? 6.6k users per MB. 512 MB RAM in smallest Galaxy container. 

Cache key is 44 characters. At 2B/character, that's 88B/key. The value is `[id, expires]`. The attributes are:
- 17 characters per Meteor id = 34 B
- Looks like Dates are Numbers, which are 8B
- How much overhead does a 2-elem array and the cache itself have? Let's say 20 B.

88 + 34 + 8 + 20 = 150 B per entry.

**Comment by stubailo** [comment]
I feel like 6.6k users is already a lot. So like 1mb is probably fine as a default.
