### ISSUE TITLE
I've started a PR for the docs using this package

### ISSUE THREAD

**Issue by timbrandin** [apollostack/meteor-integration#11]
It would be nice to see this package come to life soon, so that we can use it like this:
https://github.com/apollostack/docs/pull/106

**Comment by helfer** [comment]
@timbrandin Can you make a list of things that still need to be done to complete this package?

**Comment by timbrandin** [comment]
I'm not sure what's left, maybe @lorensr @sammkj are more aware?

**Comment by lorensr** [comment]
@timbrandin thanks, simplifying the docs was actually the goal :) 

@helfer #3 is blocking automated tests. I should have more time next week to do manual testing and add userId caching, altho could publish a version before then. the last thing was asking meteor team what they want the package to be named on atmosphere. i suggest `apollo`.

**Comment by lorensr** [comment]
@helfer this package is working, tested with https://github.com/lorensr/meteor-starter-kit/tree/apollo-package

Could someone at MDG publish this? Who should I ping for future releases? Or to add me, I'm `loren`: https://atmospherejs.com/loren/

**Comment by helfer** [comment]
@lorensr Thanks! I don't actually, know how to do that, so I'll defer to @stubailo on this one.

**Comment by stubailo** [comment]
OK! published 0.0.1 of `apollo`, and added `loren` as a maintainer!
