### ISSUE TITLE
Propose to simplify client configuration

### ISSUE THREAD

**Issue by sammkj** [apollostack/meteor-integration#12]
With the new `apollo-client` update, we have to add `queryTransformer` and `dataIdFromObject` when initializing ApolloClient and I feel like there are lots changes happening. I think it would be better if these APIs don't surface to the user. I created my own meteor-apollo integration for testing. Check it out [here](https://github.com/sammkj/apollo-tools/blob/master/src/configure-client.js).

In my repo, user will just do
```
const client = configureGraphQLClient();
```
and an ApolloClient is created.

**Comment by lorensr** [comment]
Hi sammkj, thanks for the repo link. In #2 stubailo preferred not hiding ApolloClient.

Longhand is:

```js
import ApolloClient from 'apollo-client';
import { addTypenameToSelectionSet } from 'apollo-client/queries/queryTransform';
import { createMeteorNetworkInterface, dataIdFromObject } from 'meteor/apollo';

const client = new ApolloClient({
  networkInterface: createMeteorNetworkInterface(),
  queryTransformer: addTypenameToSelectionSet,
  dataIdFromObject
});
```

Shortest, but hiding `ApolloClient`, is:
```js
import { MeteorApolloClient } from 'meteor/apollo';

const client = new MeteorApolloClient();
```

I'd like to go with this instead:

```js
import ApolloClient from 'apollo-client';
import { meteorClientConfig } from 'meteor/apollo';

const client = new ApolloClient(meteorClientConfig); // or can extend/overwrite the config
```

**Comment by stubailo** [comment]
Yeah I love the idea of just importing the config. I think that makes it clear that we aren't hacking the client in any way, while still giving people a good set of default options. As a bonus, with this approach it is possible to override the defaults.

**Comment by sammkj** [comment]
I agree with what @stubailo said. @lorensr, would you like a PR on this?

**Comment by lorensr** [comment]
Sure, thanks. warning that current master probably doesn't work yet  :)
