### ISSUE TITLE
Client module raw import not working

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-integration#14]
Top of `main-client.js` is `import '/check-npm.js';`. This works on the server, but doesn't appear to work on the client – when I run this app to test:

https://github.com/lorensr/meteor-starter-kit/tree/apollo-package

I get this error on client:

![image](https://cloud.githubusercontent.com/assets/251288/15809860/bb5bee8a-2b66-11e6-928f-c71c83fc054c.png)

(note if you run the app, you need to fix the `packages/apollo` symlink)

**Comment by lorensr** [comment]
@sammkj @timbrandin any ideas? client-side import statement inside a package throwing "cannot find module" error

**Comment by sammkj** [comment]
@lorensr ,  I think it's missing a dot in the path. `import './check-npm'`.

**Comment by lorensr** [comment]
Thank you!
