### ISSUE TITLE
Decide on API

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-integration#2]
described in readme: https://github.com/apollostack/meteor-integration

**Comment by lorensr** [comment]
Actually, I think it would be more parallel and simpler to change this:

```js
const client = new ApolloClient({
  networkInterface: createMeteorNetworkInterface()
});
```

to:

```js
const client = new MeteorApolloClient();

// options: 
{
  url
  networkInterfaceOptions
  useMeteorAccounts
  dataIdFromObject
  reduxRootKey
}

**Comment by stubailo** [comment]
I like the first one more - wrapping the API just to save like one line of boilerplate doesn't seem that useful. I'd like to eliminate meaningful work, but having the same API as the "regular" client seems like a good goal to me.

As for the server, we need to be able to set per-request options, so `createApolloServer` should be able to take a function, `createApolloServer((req) => { ... return options })`.

**Comment by lorensr** [comment]
Thanks!

options = below object?

![image](https://cloud.githubusercontent.com/assets/251288/15311370/0fb6de30-1bc8-11e6-9ebd-cb42ee5452eb.png)

So it would be 

```js
createApolloServer = (hook) => {
  options = hook(req) || {}
  options.context || options.context = {}
  options.context.userId = uid
}
```

**Comment by lorensr** [comment]
Well, return a function that given a `req`, does that

**Comment by stubailo** [comment]
Yeah, except `hook` can also be an object, so:

```js
options = (_.isFunction(hook) ? hook(req) : hook) || {};
```

Or something like that!

**Comment by lorensr** [comment]
Yep, thanks!
