### ISSUE TITLE
"Error: Meteor code must always run within a Fiber..." in Mutations only

### ISSUE THREAD

**Issue by jschlieber** [apollostack/meteor-integration#21]
Let's say we've got the following very simple GraphQL schema:
```graphql
type ContentBlock {
  _id: String
  content: String
}
type RootQuery {
  contentBlock(id: String!): ContentBlock
}
type RootMutation {
  upsertContentBlock(id: String!, content: String!): ContentBlock
}
schema {
  query: RootQuery
  mutation: RootMutation
}
```
At first let's `connect` our React component with:
```javascript
function mapQueriesToProps({ownProps: {contentId}}) {
  return {
    data: {
      query: gql`
        query getContent ($id: String!) {
          contentBlock(id: $id) {
            _id
            content
          }
        }
      `,
      variables: {id: contentId}
    }
  }
}
```
Resolvers:
```javascript
{
  RootQuery: {
    contentBlock(root, args, context) {
      try {
        return context.connectors.ContentBlock.findById(args.id);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
  },
  RootMutation: {
    upsertContentBlock(root, args, context) {
      try {
        return context.connectors.ContentBlock.upsert(args.id, args.content);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
  },
};
```
`ContentBlock` connector:
```javascript
class ContentBlockConnector {
  findById(id) {
    return ContentBlocks.findOne(id);
  }
  upsert(id, content) {
    const result = ContentBlocks.upsert({_id: id}, {
      $set: {content}
    });
    return ContentBlocks.findOne(id);
  }
}
```
_Note: `ContentBlocks` is a `Mongo.Collection`._
So far everything works fine. The `connect`ed React component successfully fetches content by `contentId`. Now let's try to add the mutation and `connect` our component with:
```javascript
function mapMutationsToProps({ownProps: {contentId}}) {
  return {
    saveContent: (content) => {
      return {
        mutation: gql`
        mutation updateContent($id: String!, $content: String!) {
          upsertContentBlock(id: $id, content: $content) {
            _id
            content
          }
        }
      `,
        variables: {
          id: contentId,
          content,
        },
      };
    },
  };
}
```
Now when we call `this.props.mutations.saveContent(content);` within our react component, we get the following Error on the server: **`Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.`**

Now let's change our mutation resolver to do the exact same thing the query resolver does:
```javascript
{
  RootQuery: {
    contentBlock(root, args, context) {
      try {
        return context.connectors.ContentBlock.findById(args.id);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
  },
  RootMutation: {
    upsertContentBlock(root, args, context) {
      try {
        return context.connectors.ContentBlock.findById(args.id);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
  },
};
```
Calling `this.props.mutations.saveContent(content);` now still yields an **`Error: Can't wait without a fiber`**.

Now try to use `Meteor.bindEnvironment` to wrap the resolver (note that the Meteor package already does `WebApp.connectHandlers.use(Meteor.bindEnvironment(graphQLServer));`) :
```javascript
{
  ...
  RootMutation: {
    upsertContentBlock: Meteor.bindEnvironment(function (root, args, context) {
      ...
    }),
  },
}
```
No more error, but inspecting the `GraphQLResult` from `this.props.mutations.saveContent(content).then(GraphQLResult => ...)` shows that its `data` property is `{upsertContentBlock: null, __typename: "RootMutation"}` where `upsertContentBlock` shouldn't be `null` because the resolver returns an object.

Is anyone experiencing the same problems when using Apollo with Meteor? Can someone explain what's going on there and why calling methods on `Mongo.Collection`s work with query resolvers and don't work (as expected) with mutation resolvers?

Thanks in advance.

### Versions
```javascript
{
  "apollo-client": "^0.3.24",
  "apollo-server": "^0.1.5",
  "react": "^15.1.0",
  "react-apollo": "^0.3.13",
}
```

**Comment by twelvearrays** [comment]
Have you tried async in front of your mutation call in your resolvers?

`RootMutation: {
    **aysnc** upsertContentBlock(root, args, context) {
      try {
        return context.connectors.ContentBlock.findById(args.id);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
  },
};`

**Comment by lorensr** [comment]
Could try both async and await:

```js
  RootMutation: {
    async upsertContentBlock(root, args, context) {
      try {
        return await context.connectors.ContentBlock.findById(args.id);
      } catch (err) {
        console.log(err.stack);
        throw err;
      }
    },
```

**Comment by lorensr** [comment]
Do you still see this when using `apollo@0.1.0`?

**Comment by nicolaslopezj** [comment]
Why I have to use async in mutations to run in fibers?
