### ISSUE TITLE
Update to apollo-client 0.4.1

### ISSUE THREAD

**Issue by paralin** [apollostack/meteor-integration#22]
```
WARNING: npm peer requirements (for apollo) not installed:
 - apollo-client@0.4.1 installed, apollo-client@^0.3.12 needed
```

:+1:

**Comment by lorensr** [comment]
Thanks! Try `meteor add apollo@0.1.0-beta` and let me know if it works ☺️ Doesn't look like any of the `0.4.0` breaking changes should affect this package.

**Comment by hlehmann** [comment]
I always get this error with apollo-client@0.4.11 and apollo-server@0.1.5 
```
{
  "errors": [
    {
      "message": "source.body.split is not a function"
    }
  ]
}
```

Should we use apollo-server@0.2.1 ?

**Comment by lorensr** [comment]
Yeah thanks, we need to update this package for `0.2.1` (see #24). Let's see if you still get the error after that happens

**Comment by GrandathePanda** [comment]
WARNING: npm peer requirements (for apollo) not installed:
 - apollo-client@^0.4.11 not installed.

Read more about installing npm peer dependencies: --

I'm seeing the above every time logged to the console from some error handler some where, I have meteor apollo beta-2 currently installed and of course apollo-client@^0.4.11 installed.

**Comment by paralin** [comment]
@grandathepanda it's up to you to install the peer dependencies yourself, so npm install apollo-client

**Comment by lorensr** [comment]
npm install apollo-client@* should get you to the most recent version!

**Comment by GrandathePanda** [comment]
That was my point, it already is the most updated according to my package.json

**Comment by lorensr** [comment]
@GrandathePanda Oh, sorry about that! You will see that error message in the client console until you add `import ApolloClient from 'apollo-client';` to one of your client files. Does that fix it for you? (I've submitted this bug to https://github.com/tmeasday/check-npm-versions/issues/9)

**Comment by rdickert** [comment]
I got apollo client 0.4 working. I haven't figured out everything, and the odd thing is it *appeared* to require a local copy of the meteor-integration package (see the code for the sha of the commit I used). My code is [here](https://github.com/okgrow/meteor-starter-kit/commit/acd4413a1b6aacde41a0c75d373c3c7968efe541) - see also my comments [here](https://github.com/apollostack/meteor-starter-kit/pull/22). Please comment if you learn more or find the code does/doesn't work for you.

**Comment by rdickert** [comment]
This is working now (see the [meteor-starter-kit](https://github.com/apollostack/meteor-starter-kit)).  Should be able to close this.
