### ISSUE TITLE
Provide a way for GraphiQL user to be logged in

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-integration#29]
There is a version of graphiql that supports HTTP headers, in which case we could use the auth header that the meteor app uses:

https://github.com/graphql/express-graphql/issues/101

Or maybe we could put the auth token in a query variable?

Thanks @rdickert for the good idea

**Comment by stubailo** [comment]
In the Meteor case, it could be easy to have GraphiQL get the auth token from local storage? But that requires a custom GraphiQL implementation, which wouldn't be ideal.

**Comment by lorensr** [comment]
Yep same domain so same localstorage

**Comment by nicolaslopezj** [comment]
Here is an example that only overrides the fetcher. I think this should be the way we achieve this.

https://github.com/graphql/graphiql/blob/master/example/index.html#L98

**Comment by lorensr** [comment]
Oh nice, that's great, thanks ☺️
