### ISSUE TITLE
Calling Meteor.logout() doesn't do anything.

### ISSUE THREAD

**Issue by vangorra** [apollostack/meteor-integration#30]
When calling Meteor.logout(), the context.userId on the server side should be set to undefined. Instead, it is still set as the id for the previously logged in user. If I restart the server process, the cached userId is cleared and all is well again.

**Comment by lorensr** [comment]
This should be fixed in `v0.0.4` – does that work for you?

**Comment by vangorra** [comment]
This should work. What is the estimated time line for this package's 0.4.0 release?

**Comment by lorensr** [comment]
`v0.0.4` was released two days ago: 

https://atmospherejs.com/meteor/apollo

**Comment by vangorra** [comment]
Yep. 0.0.4 works. Thanks.
