### ISSUE TITLE
Peer dependency - unnecessary warnings

### ISSUE THREAD

**Issue by rdickert** [apollostack/meteor-integration#31]
I'm getting `WARNING: npm peer requirements (for apollo) not installed: graphql@0.7.0 installed, graphql@^0.6.2 needed`. Everything seems to work fine, so that dependency should probably be updated to add 0.7.x.

Also there is a dependency on `'apollo-client': '^0.4.11'`, but it seems to work fine with client 0.3.x. I haven't tested extensively, but I don't see anything that touches API changes for 0.4.

**Comment by lorensr** [comment]
Thanks :) Looks like it calls `semver.range` – what do you recommend for the version numbers? 

https://github.com/tmeasday/check-npm-versions/blob/master/check-npm-versions.js#L11

**Comment by stubailo** [comment]
@tmeasday any ideas?

**Comment by helfer** [comment]
Just add graphql 0.7.0 to the supported peer versions, and we're good. You can probably deprecate 0.6 and below.

**Comment by tmeasday** [comment]
Semver is pretty flexible. I think you can do like `^0.6.0 | ^0.7.0` if you want

**Comment by helfer** [comment]
I think it's `||`, but yeah, you can do that. I just wonder if there's a reason for people to use 0.6.0 at all, or if it would be better to get them to upgrade.

**Comment by lorensr** [comment]
Thanks all, included in `apollo@0.1.0`:

![image](https://cloud.githubusercontent.com/assets/251288/18403921/8cb2cc62-76b5-11e6-8c9c-76996f617fef.png)
