### ISSUE TITLE
Is there a way to turn on query batching?

### ISSUE THREAD

**Issue by townmulti** [apollostack/meteor-integration#38]
http://dev.apollodata.com/core/network.html#query-batching

**Comment by lorensr** [comment]
> To turn on query batching, pass the shouldBatch: true option to the ApolloClient constructor. 

Yep, you can modify the object you pass to the constructor:

http://dev.apollodata.com/core/meteor.html#Client

```js
import { meteorClientConfig } from 'meteor/apollo';
const myConfig = meteorClientConfig()
myConfig.shouldBatch = true;
const client = new ApolloClient(myConfig);
```

**Comment by smeijer** [comment]
Do I understand correctly that this isn't supported any longer with the `meteor-integration` package?

The settings from the docs aren't affecting the generated requests, and the [`network config`][1] in this package doesn't match the required [`network config`][2] either.

[1]: https://github.com/apollostack/meteor-integration/blob/master/main-client.js#L7
[2]: http://dev.apollodata.com/core/network.html#query-batching

**Comment by xavcz** [comment]
Yep, it's not supported at the moment, query batching got updated: http://dev.apollodata.com/core/network.html#query-batching

However, it's not difficult to implement on the Apollo Client side:
>To use batching, simply pass a BatchedNetworkInterface to the ApolloClient constructor.

```
import ApolloClient, { createBatchingNetworkInterface } from 'apollo-client';

const batchingNetworkInterface = createBatchingNetworkInterface({
  uri: 'localhost:3000',
  batchInterval: 10,
  opts: {
    // Options to pass along to `fetch`
  }
});
```

I'll do a PR for that 🙂
