### ISSUE TITLE
graphiql broken with last apollo version

### ISSUE THREAD

**Issue by miwo100** [apollostack/meteor-integration#41]
the latest apollo version 0.1.2 seems to be broken, localhost:3000/graphiql fails with:

```TypeError: undefined is not an object (evaluating 't.toString')```

both with Meteor 1.4.1.1 and 1.4.1.2

version 0.1.1 runs fine.

**Comment by rdickert** [comment]
@miwo100 perhaps you need to update your npm dependencies? 0.1.2 requires apollo-server 0.3 (but you should be getting a runtime warning from Meteor if you didn't meet this requirement). I have a working app with apollo@0.1.2 on Meteor 1.4.1.1 with these installed graphql-related modules. You can check your list with `npm ls --prod --depth 0`.

├── apollo-client@0.4.20
├── apollo-server@0.3.2
├── graphql@0.7.1
├── graphql-tag@0.1.14
├── graphql-tools@0.6.6
├── graphql-typings@0.0.1-beta-2

**Comment by miwo100** [comment]
@rdickert I got the following level 0 deps:
├── apollo-client@0.4.20
├── apollo-server@0.3.2
├── graphql@0.7.1
├── graphql-tools@0.7.2

I hadn't installed graphql-tag and graphql-typings.
I will come back later when I tried adding these dependencies...

**Comment by miwo100** [comment]
@rdickert sorry, was only a problem with safari. Chrome is ok.
Now I ve got these dependencies:

├── apollo-client@0.4.20
├── apollo-server@0.3.2
├── graphql@0.7.1
├── graphql-tag@0.1.14
├── graphql-tools@0.7.2
├── graphql-typings@0.0.1-beta-2

and in chrome everything runs fine. 

But not in Safari (Version 10.0 (10602.1.50.0.10)).

**Comment by rdickert** [comment]
@miwo100 That's odd that it is a problem with just one browser. Did you make sure to log in to your app in safari before going to graphiql? The login token does not transfer between browsers.

**Comment by miwo100** [comment]
@rdickert, sorry but I just realized that http://localhost:3000/graphiql now runs ok on both safari and chrome, but the application itself at http://localhost:3000 works only with chrome but not with safari.

**Comment by miwo100** [comment]
it might have to do something with angular 2, because when I comment out the app module from  being loaded it safari won't hang anymore:

```
import 'angular2-meteor-polyfills';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { Meteor } from "meteor/meteor";
import { AppModule } from './imports/app.module';

enableProdMode();

Meteor.startup(() => {
   // next line runs fine with chrome but hangs with safari 10.0:
   platformBrowserDynamic().bootstrapModule(AppModule);
});
```

**Comment by Urigo** [comment]
@miwo100 does this relate to `angular2-apollo` or `Angular` by itself?
if you remove apollo from your app, does it run on Safari?
maybe this issue should go to the Angular repo?

**Comment by miwo100** [comment]
@Urigo thanks for the hint. I removed angular2-apollo, leaving the app without any data access.

Chrome running fine:
![image](https://cloud.githubusercontent.com/assets/5810399/19637841/3b0fd118-99d1-11e6-9cae-6e9ae6f9c8a0.png)

Safari hanging:
![image](https://cloud.githubusercontent.com/assets/5810399/19637705/b3cc206c-99d0-11e6-84d9-b44a5607ec7a.png)

**Comment by Urigo** [comment]
so I guess it's worth opening an issue on the Angular repo

**Comment by miwo100** [comment]
With the latest version of angular even Safari gets it fine 👍  Before I used version 2.0.1. of angular dependencies that failed with Safari.

Currently working dependencies:
```
    "@angular/common": "~2",
    "@angular/compiler": "~2",
    "@angular/core": "~2",
    "@angular/forms": "~2",
    "@angular/http": "~2",
    "@angular/platform-browser": "~2",
    "@angular/platform-browser-dynamic": "~2",
    "@angular/router": "~3",
```
