### ISSUE TITLE
Default port? 

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-integration#9]
Currently 4000. From @timbrandin:

![image](https://cloud.githubusercontent.com/assets/251288/15687103/01b7061e-2741-11e6-82c2-f1cb9e449a5a.png)

Should we set the default port to 80 and just note to not put an asset or route at `/graphql`? 

We should at least support passing 80 as a config param.

**Comment by timbrandin** [comment]
https://github.com/apollostack/meteor-integration/pull/10
